services:
  redis:
    image: redis
    ports:
      - 6379:6379

  web:
    build: ./
    volumes:
      - ./:/var/app
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - REDIS_URL=redis://redis:6379
    links:
      - redis
    depends_on:
      - redis
    command: sh -c 'npm i && npm run start'
